name: get_weather
description: A new Flutter application to fecth real time weather using openWeather API


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^5.2.0
  http: ^0.12.0+4
  flutter_spinkit: "^4.1.1"
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 900